# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='rnn_ur5',
  serialized_pb='\n\ndata.proto\x12\x07rnn_ur5\"\xf0\x01\n\x08Sequence\x12)\n\x04\x65nds\x18\x01 \x02(\x0b\x32\x1b.rnn_ur5.Sequence.EndPoints\x12(\n\x06thetas\x18\x02 \x03(\x0b\x32\x18.rnn_ur5.Sequence.Thetas\x12\"\n\x03xyz\x18\x03 \x03(\x0b\x32\x15.rnn_ur5.Sequence.XYZ\x1a\x35\n\tEndPoints\x12\x14\n\x0cinitial_pose\x18\x01 \x03(\x01\x12\x12\n\nfinal_pose\x18\x02 \x03(\x01\x1a\x1e\n\x06Thetas\x12\x14\n\x0ctheta_values\x18\x01 \x03(\x01\x1a\x14\n\x03XYZ\x12\r\n\x05poses\x18\x01 \x03(\x01')




_SEQUENCE_ENDPOINTS = _descriptor.Descriptor(
  name='EndPoints',
  full_name='rnn_ur5.Sequence.EndPoints',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='initial_pose', full_name='rnn_ur5.Sequence.EndPoints.initial_pose', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='final_pose', full_name='rnn_ur5.Sequence.EndPoints.final_pose', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=157,
  serialized_end=210,
)

_SEQUENCE_THETAS = _descriptor.Descriptor(
  name='Thetas',
  full_name='rnn_ur5.Sequence.Thetas',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='theta_values', full_name='rnn_ur5.Sequence.Thetas.theta_values', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=212,
  serialized_end=242,
)

_SEQUENCE_XYZ = _descriptor.Descriptor(
  name='XYZ',
  full_name='rnn_ur5.Sequence.XYZ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='poses', full_name='rnn_ur5.Sequence.XYZ.poses', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=244,
  serialized_end=264,
)

_SEQUENCE = _descriptor.Descriptor(
  name='Sequence',
  full_name='rnn_ur5.Sequence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ends', full_name='rnn_ur5.Sequence.ends', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='thetas', full_name='rnn_ur5.Sequence.thetas', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xyz', full_name='rnn_ur5.Sequence.xyz', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SEQUENCE_ENDPOINTS, _SEQUENCE_THETAS, _SEQUENCE_XYZ, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=264,
)

_SEQUENCE_ENDPOINTS.containing_type = _SEQUENCE;
_SEQUENCE_THETAS.containing_type = _SEQUENCE;
_SEQUENCE_XYZ.containing_type = _SEQUENCE;
_SEQUENCE.fields_by_name['ends'].message_type = _SEQUENCE_ENDPOINTS
_SEQUENCE.fields_by_name['thetas'].message_type = _SEQUENCE_THETAS
_SEQUENCE.fields_by_name['xyz'].message_type = _SEQUENCE_XYZ
DESCRIPTOR.message_types_by_name['Sequence'] = _SEQUENCE

class Sequence(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class EndPoints(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SEQUENCE_ENDPOINTS

    # @@protoc_insertion_point(class_scope:rnn_ur5.Sequence.EndPoints)

  class Thetas(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SEQUENCE_THETAS

    # @@protoc_insertion_point(class_scope:rnn_ur5.Sequence.Thetas)

  class XYZ(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SEQUENCE_XYZ

    # @@protoc_insertion_point(class_scope:rnn_ur5.Sequence.XYZ)
  DESCRIPTOR = _SEQUENCE

  # @@protoc_insertion_point(class_scope:rnn_ur5.Sequence)


# @@protoc_insertion_point(module_scope)
